name: Deploy Vite React to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is fetched

      - name: Setup Git Config
        run: |
          git config --global user.email "rahulthakur.official6@gmail.com"
          git config --global user.name "rahulthakurofficial"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deployment branch
          folder: dist  # Vite's output build folder
          token: ${{ secrets.GH_TOKEN }}  # Ensure authentication
